name: And Before Long
favicon: null
layout_spectrum: 1
typography_spectrum: 0.09424
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0bb31'
    - '#57b5c1'
    - '#f05d67'
    - '#34343e'
    - '#ffffff'
  brandStrength: 0.875
  lightness: 0.875
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
